name=" Rohit Karkale"
print(len(name))
print(name.find("r"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.count("o"))
print(name.isdigit())
print(name.isalpha())
print(name.replace("r","o"))
print(name*3)