print("Hello")
print("Welcome to FDP on AI")
print(len("Hello I am Rohit "))
str='Hello VIIT University'
print(str)
print(str[0])
print(str[3])
print(str[2:])
print(str[:5])
print(str[:])
print(str + ", I am Rohit ")
print(str.upper())
print(str.find("o"))
print(str.split())
print(str.count("t"))
print("Enter name here {} then also {}".format("Rohit","Rohan"))
print("The color are {2} {1} {0}.".format("red","blue","Green"))
print("first object : {a}, second object : {b}, Third object: {c}".format(a=1,b="Two",c=3.3))

